"""
Django settings for punkycuts project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import django_heroku, postman
from os import getenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lj=l)3ypkdzvq715)9y0s%5ph7_%+h2teutt@^y^i7+ad^!62z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if DEBUG:
    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)

ALLOWED_HOSTS = [
    getenv('APP_HOST')
]

INTERNAL_IPS = [
    '127.0.0.1'
]
SECURE_SSL_REDIRECT = True
CSRF_USE_SESSIONS = True

SITE_ID = 1

LANGUAGES = [
    ('en', 'English')
]

X_FRAME_OPTIONS = 'SAMEORIGIN'

CMS_TEMPLATES = [
    ('home.html', 'Home page template'),
]
# Application definition

INSTALLED_APPS = [
    #'djangocms_admin_style',
    'store_index',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'sekizai',
    'cms',
    'menus',
    'treebeard',
    'channels',
    #'chat',
    #'dj-pagination'
    'postman',
    'rest_framework',
    'PIL'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',
]

ROOT_URLCONF = 'punkycuts.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            'C:/Users/jenni/Documents/SCHOOL/Fall2021_LASTSEMESTER!/CAPSTONE/punky-cuts/punkycuts/templates'
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sekizai.context_processors.sekizai',
                'cms.context_processors.cms_settings',
                'django.template.context_processors.i18n'
            ],
        },
    },
]

WSGI_APPLICATION = 'punkycuts.wsgi.application'

# Channels
ASGI_APPLICATION = "punkycuts.asgi.application"

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'punkycuts$punky_cuts_db',
        'USER': 'punkycuts',
        'PASSWORD': 'database',
        'HOST': 'punkycuts.mysql.pythonanywhere-services.com',
    },
     'TEST': {
          'NAME': '<your username>$test_<your database name>',
    }
}
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    "C:\\Users\\jenni\\Documents\\SCHOOL\\Fall2021_LASTSEMESTER!\\CAPSTONE\\punky-cuts\\punkycuts\\static",
    "C:\\Users\\jenni\\Documents\\SCHOOL\\Fall2021_LASTSEMESTER!\\CAPSTONE\\punky-cuts\\punkycuts\\store_index\\static\\store_index"
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Activate Django-Heroku.
django_heroku.settings(locals())

TEMPLATE_CONTEXT_PROCESSORS = [
    'postman.context_processors.inbox'
]

LOGIN_REDIRECT_URL = 'profile'

POSTMAN_AUTO_MODERATE_AS = True

SESSION_COOKIE_SECURE=True 
SESSION_COOKIE_SAMESITE = None 
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = None

# EMAIL CONFIG 

EMAIL_FROM_USER = 'contactpunkycuts@gmail.com'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'contactpunkycuts@gmail.com'
EMAIL_HOST_PASSWORD = 'Capstone_Project01!'