# Generated by Django 3.2.8 on 2021-11-07 19:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('ShippingAddress', models.CharField(max_length=100)),
                ('BillingAddress', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=50)),
                ('ZipCode', models.CharField(max_length=5)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDate', models.DateTimeField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_index.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductDesc', models.CharField(max_length=200)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(help_text='Html2canvas screenshot', upload_to='img/screenshots/')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_index.order')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_index.product')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_index.state'),
        ),
    ]
