# Generated by Django 3.2.8 on 2021-11-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_index', '0002_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='OrderDate',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ProductDesc',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ProductName',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='BillingAddress',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='City',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ShippingAddress',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='State',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Username',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ZipCode',
        ),
    ]
