# Generated by Django 3.2.8 on 2021-11-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_index', '0003_auto_20211108_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='LastName',
        ),
    ]
