# Generated by Django 3.2.8 on 2021-11-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_index', '0005_auto_20211108_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Password',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Username',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
