# Generated by Django 3.2.8 on 2021-11-13 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_index', '0006_auto_20211108_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'category',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'status',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'product'},
        ),
        migrations.AddField(
            model_name='product',
            name='Slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateAdded', models.DateTimeField(auto_created=True, editable=False)),
                ('FileName', models.CharField(max_length=50)),
                ('Picture', models.ImageField(upload_to=None)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_index.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=None)),
                ('Price', models.IntegerField(default=None)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_index.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Categories',
            field=models.ManyToManyField(to='store_index.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store_index.status'),
        ),
    ]
