# Generated by Django 3.2.8 on 2021-11-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_index', '0008_auto_20211113_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='PhoneNumber',
            field=models.CharField(default=None, max_length=15, unique=True),
        ),
    ]
