# Generated by Django 3.2.8 on 2021-11-14 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_index', '0009_alter_customer_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='BillingAddress',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='BillingCity',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='BillingState',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='BillingState', to='store_index.state'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='BillingZipCode',
            field=models.CharField(blank=True, default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PhoneNumber',
            field=models.CharField(blank=True, default=None, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ShippingAddress',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ShippingCity',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ShippingState',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ShippingState', to='store_index.state'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ShippingZipCode',
            field=models.CharField(blank=True, default=None, max_length=5),
        ),
    ]
