# Generated by Django 3.2.8 on 2021-11-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_index', '0010_auto_20211113_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Email',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PhoneNumber',
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
    ]
