# Generated by Django 3.2.8 on 2021-11-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_index', '0013_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Email',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
