# Generated by Django 3.2.8 on 2021-11-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0002_alter_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
